const express=require('express'),rateLimit=require('express-rate-limit'),multer=require('multer'),fs=require('fs'),path=require('path');const config=require('../config');const Job=require('../models/MediaJob');const Guild=require('../models/GuildConfig');const {ALL,canConvert,normalize}=require('../utils/formats');const {enqueueDownload,enqueueConvert}=require('../services/jobs');const {downloadStream}=require('../services/gridfs');const {ensure,remove}=require('../utils/files');const router=express.Router();const upload=multer({dest:config.tempDir,limits:{fileSize:config.maxUploadMB*1048576}});const limiter=rateLimit({windowMs:15*60*1000,max:100,standardHeaders:true,legacyHeaders:false});router.use(limiter);
function validUrl(s){try{const u=new URL(s);return ['http:','https:'].includes(u.protocol)&&!['localhost','127.0.0.1','0.0.0.0','::1'].includes(u.hostname)}catch{return false}}
router.get('/health',(req,res)=>res.json({ok:true,service:'MediaX',time:new Date().toISOString()}));router.get('/formats',(req,res)=>res.json({formats:ALL,conversionExamples:{image:['png','jpg','jpeg','webp','gif','pdf'],video:['mp4','mov','webm','avi','mkv','gif','mp3','wav','flac','aac','ogg','m4a'],audio:['mp3','wav','flac','aac','ogg','m4a']}}));router.get('/formats/can-convert',(req,res)=>res.json({from:normalize(req.query.from),to:normalize(req.query.to),allowed:canConvert(req.query.from,req.query.to)}));
router.post('/download',async(req,res)=>{try{const {url,format='mp4',guildId=null,userId='api'}=req.body;if(!validUrl(url))return res.status(400).json({error:'Valid HTTP/HTTPS URL required'});if(!ALL.includes(normalize(format)))return res.status(400).json({error:'Unsupported format'});if(guildId){const g=await Guild.findOne({guildId});if(g&&!g.enabled)return res.status(403).json({error:'MediaX is disabled for this server'})}const job=await Job.create({guildId,userId,type:'download',source:url,outputFormat:normalize(format)});enqueueDownload(job).catch(()=>{});res.status(202).json({jobId:job._id,status:'queued',statusUrl:`${config.publicBaseUrl}/api/jobs/${job._id}`})}catch(e){res.status(500).json({error:e.message})}});
router.post('/convert',upload.single('file'),async(req,res)=>{try{if(!req.file)return res.status(400).json({error:'file is required'});const inputFormat=normalize(req.body.inputFormat||path.extname(req.file.originalname));const outputFormat=normalize(req.body.outputFormat);if(!canConvert(inputFormat,outputFormat)){await remove(req.file.path);return res.status(400).json({error:`Conversion from ${inputFormat} to ${outputFormat} is not supported`})}const job=await Job.create({guildId:req.body.guildId||null,userId:req.body.userId||'api',type:'convert',inputFormat,outputFormat});enqueueConvert(job,req.file.path,inputFormat).catch(()=>{});res.status(202).json({jobId:job._id,status:'queued',statusUrl:`${config.publicBaseUrl}/api/jobs/${job._id}`})}catch(e){if(req.file)await remove(req.file.path);res.status(500).json({error:e.message})}});
router.get('/jobs/:id',async(req,res)=>{const j=await Job.findById(req.params.id).select('-source');if(!j)return res.status(404).json({error:'Job not found'});res.json(j)});
router.get('/files/:id',async(req,res)=>{try{const j=await Job.findOne({gridfsFileId:req.params.id,status:'completed'});if(!j)return res.status(404).json({error:'File not found or expired'});res.setHeader('Content-Disposition',`attachment; filename="${j.filename}"`);res.setHeader('Content-Length',String(j.sizeBytes));downloadStream(req.params.id).on('error',()=>res.end()).pipe(res)}catch(e){res.status(404).json({error:'File not found'})}});
router.get('/history',async(req,res)=>{const q={};if(req.query.guildId)q.guildId=req.query.guildId;if(req.query.userId)q.userId=req.query.userId;res.json(await Job.find(q).sort({createdAt:-1}).limit(100).select('-source'))});
module.exports=router;
