const fs=require('fs'),path=require('path'),os=require('os'),crypto=require('crypto'),{spawn}=require('child_process');
const ffmpeg=require('fluent-ffmpeg'),sharp=require('sharp'),{PDFDocument}=require('pdf-lib');
const config=require('../config');const {ensure,remove,safeName}=require('../utils/files');const {category,normalize,canConvert}=require('../utils/formats');
ensure(config.tempDir);let ff=config.ffmpegPath||require('ffmpeg-static');let fp=config.ffprobePath||require('ffprobe-static').path;ffmpeg.setFfmpegPath(ff);if(fp)ffmpeg.setFfprobePath(fp);
function temp(ext='bin'){return path.join(config.tempDir,`${crypto.randomBytes(16).toString('hex')}.${ext}`)}
function run(cmd,args,seconds,onData){return new Promise((resolve,reject)=>{const p=spawn(cmd,args,{shell:false});let err='',done=false;const timer=setTimeout(()=>{if(done)return;done=true;try{p.kill('SIGKILL')}catch{}reject(new Error('Process timed out'))},seconds*1000);p.stderr.on('data',d=>{err+=d.toString();if(onData)onData(d.toString())});p.on('error',e=>{if(done)return;done=true;clearTimeout(timer);reject(e)});p.on('close',c=>{if(done)return;done=true;clearTimeout(timer);c===0?resolve():reject(new Error(err.trim().slice(-3000)||`process exited ${c}`))})})}
async function download(url,format,onProgress){format=normalize(format);const out=temp(format==='mp3'||format==='m4a'?format:'bin');await remove(out);const args=['--no-playlist','--no-warnings','--restrict-filenames','-o',out];if(format==='mp3'||format==='m4a')args.push('-x','--audio-format',format,'--audio-quality','0');else args.push('-f','bv*+ba/b','--merge-output-format',format);args.push(url);await run(config.ytdlpPath,args,config.maxDownloadSeconds,onProgress);let actual=out;if(!fs.existsSync(actual)){const base=path.parse(out).name;const hit=fs.readdirSync(config.tempDir).find(x=>x.startsWith(base+'.'));if(hit)actual=path.join(config.tempDir,hit)}if(!fs.existsSync(actual))throw new Error('yt-dlp finished but no output file was produced');const st=await fs.promises.stat(actual);if(st.size>config.maxOutputMB*1048576){await remove(actual);throw new Error('Output exceeds MAX_OUTPUT_MB')}return {path:actual,filename:safeName(path.basename(actual)),size:st.size}}
function ffconvert(input,out,format,seconds){return new Promise((resolve,reject)=>{let c=ffmpeg(input);switch(format){case'mp3':c.noVideo().audioCodec('libmp3lame').audioBitrate('192k');break;case'wav':c.noVideo().audioCodec('pcm_s16le');break;case'flac':c.noVideo().audioCodec('flac');break;case'aac':c.noVideo().audioCodec('aac').audioBitrate('192k');break;case'ogg':c.noVideo().audioCodec('libvorbis').audioBitrate('192k');break;case'm4a':c.noVideo().audioCodec('aac').audioBitrate('192k');break;case'mp4':c.videoCodec('libx264').audioCodec('aac').outputOptions('-movflags','+faststart');break;case'mov':c.videoCodec('libx264').audioCodec('aac');break;case'webm':c.videoCodec('libvpx-vp9').audioCodec('libopus');break;case'avi':c.videoCodec('mpeg4').audioCodec('libmp3lame');break;case'mkv':c.videoCodec('libx264').audioCodec('aac');break;case'gif':c.outputOptions('-vf','fps=12,scale=720:-1:flags=lanczos');break;default:return reject(new Error('Unsupported output format'))}let timer=setTimeout(()=>{try{c.kill('SIGKILL')}catch{}reject(new Error('Conversion timed out'))},seconds*1000);c.on('end',()=>{clearTimeout(timer);resolve()}).on('error',e=>{clearTimeout(timer);reject(e)}).save(out)})}
async function imageConvert(input,out,format){const s=sharp(input);if(['jpg','jpeg'].includes(format))return s.jpeg({quality:90}).toFile(out);if(format==='png')return s.png().toFile(out);if(format==='webp')return s.webp({quality:90}).toFile(out);if(format==='gif')return s.gif().toFile(out);throw new Error('Unsupported image output')}
async function imagesToPdf(inputs,out){const pdf=await PDFDocument.create();for(const p of inputs){const ext=path.extname(p).slice(1).toLowerCase();let b=await fs.promises.readFile(p);let image;if(['jpg','jpeg'].includes(ext))image=await pdf.embedJpg(b);else{if(ext!=='png')b=await sharp(p).png().toBuffer();image=await pdf.embedPng(b)}const page=pdf.addPage([image.width,image.height]);page.drawImage(image,{x:0,y:0,width:image.width,height:image.height})}await fs.promises.writeFile(out,await pdf.save())}
async function convert(input,inputFormat,outputFormat){inputFormat=normalize(inputFormat);outputFormat=normalize(outputFormat);if(!canConvert(inputFormat,outputFormat))throw new Error(`Conversion from ${inputFormat} to ${outputFormat} is not supported`);const out=temp(outputFormat);const a=category(inputFormat),b=category(outputFormat);if(outputFormat==='pdf'&&a==='image')await imagesToPdf([input],out);else if(a==='image'&&b==='image')await imageConvert(input,out,outputFormat);else await ffconvert(input,out,outputFormat,config.maxConvertSeconds);const st=await fs.promises.stat(out);if(st.size>config.maxOutputMB*1048576){await remove(out);throw new Error('Output exceeds MAX_OUTPUT_MB')}return {path:out,filename:`mediax.${outputFormat}`,size:st.size}}
async function inspect(file){return new Promise((resolve,reject)=>ffmpeg.ffprobe(file,(e,d)=>e?reject(e):resolve(d)))}
module.exports={download,convert,inspect};
